# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  discord-webhook-url:  # id of input
    description: 'Discord Webhook URL'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}